/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MisPedidosRouteImport } from './routes/mis-pedidos'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as ApiPublicWebhooksBinanceRouteImport } from './routes/api/public/webhooks/binance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPedidosRoute = MisPedidosRouteImport.update({
  id: '/mis-pedidos',
  path: '/mis-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksBinanceRoute =
  ApiPublicWebhooksBinanceRouteImport.update({
    id: '/api/public/webhooks/binance',
    path: '/api/public/webhooks/binance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/producto/$id': typeof ProductoIdRoute
  '/api/public/webhooks/binance': typeof ApiPublicWebhooksBinanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/producto/$id': typeof ProductoIdRoute
  '/api/public/webhooks/binance': typeof ApiPublicWebhooksBinanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/producto/$id': typeof ProductoIdRoute
  '/api/public/webhooks/binance': typeof ApiPublicWebhooksBinanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/mis-pedidos'
    | '/producto/$id'
    | '/api/public/webhooks/binance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/mis-pedidos'
    | '/producto/$id'
    | '/api/public/webhooks/binance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/mis-pedidos'
    | '/producto/$id'
    | '/api/public/webhooks/binance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  MisPedidosRoute: typeof MisPedidosRoute
  ProductoIdRoute: typeof ProductoIdRoute
  ApiPublicWebhooksBinanceRoute: typeof ApiPublicWebhooksBinanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pedidos': {
      id: '/mis-pedidos'
      path: '/mis-pedidos'
      fullPath: '/mis-pedidos'
      preLoaderRoute: typeof MisPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/binance': {
      id: '/api/public/webhooks/binance'
      path: '/api/public/webhooks/binance'
      fullPath: '/api/public/webhooks/binance'
      preLoaderRoute: typeof ApiPublicWebhooksBinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  MisPedidosRoute: MisPedidosRoute,
  ProductoIdRoute: ProductoIdRoute,
  ApiPublicWebhooksBinanceRoute: ApiPublicWebhooksBinanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
