/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MisPedidosRouteImport } from './routes/mis-pedidos'
import { Route as RecargarSaldoRouteImport } from './routes/recargar-saldo'
import { Route as SaldoRouteImport } from './routes/saldo'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as ApiPublicIpRouteImport } from './routes/api/public/ip'
import { Route as ApiPublicIpWatchRouteImport } from './routes/api/public/ip-watch'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicWebhooksBinanceRouteImport } from './routes/api/public/webhooks/binance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPedidosRoute = MisPedidosRouteImport.update({
  id: '/mis-pedidos',
  path: '/mis-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecargarSaldoRoute = RecargarSaldoRouteImport.update({
  id: '/recargar-saldo',
  path: '/recargar-saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const SaldoRoute = SaldoRouteImport.update({
  id: '/saldo',
  path: '/saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIpRoute = ApiPublicIpRouteImport.update({
  id: '/api/public/ip',
  path: '/api/public/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIpWatchRoute = ApiPublicIpWatchRouteImport.update({
  id: '/api/public/ip-watch',
  path: '/api/public/ip-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksBinanceRoute =
  ApiPublicWebhooksBinanceRouteImport.update({
    id: '/api/public/webhooks/binance',
    path: '/api/public/webhooks/binance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/recargar-saldo': typeof RecargarSaldoRoute
  '/saldo': typeof SaldoRoute
  '/producto/$id': typeof ProductoIdRoute
  '/api/public/ip': typeof ApiPublicIpRoute
  '/api/public/ip-watch': typeof ApiPublicIpWatchRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/webhooks/binance': typeof ApiPublicWebhooksBinanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/recargar-saldo': typeof RecargarSaldoRoute
  '/saldo': typeof SaldoRoute
  '/producto/$id': typeof ProductoIdRoute
  '/api/public/ip': typeof ApiPublicIpRoute
  '/api/public/ip-watch': typeof ApiPublicIpWatchRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/webhooks/binance': typeof ApiPublicWebhooksBinanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/recargar-saldo': typeof RecargarSaldoRoute
  '/saldo': typeof SaldoRoute
  '/producto/$id': typeof ProductoIdRoute
  '/api/public/ip': typeof ApiPublicIpRoute
  '/api/public/ip-watch': typeof ApiPublicIpWatchRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/webhooks/binance': typeof ApiPublicWebhooksBinanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/mis-pedidos'
    | '/recargar-saldo'
    | '/saldo'
    | '/producto/$id'
    | '/api/public/ip'
    | '/api/public/ip-watch'
    | '/api/public/img/$'
    | '/api/public/telegram/webhook'
    | '/api/public/webhooks/binance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/mis-pedidos'
    | '/recargar-saldo'
    | '/saldo'
    | '/producto/$id'
    | '/api/public/ip'
    | '/api/public/ip-watch'
    | '/api/public/img/$'
    | '/api/public/telegram/webhook'
    | '/api/public/webhooks/binance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/mis-pedidos'
    | '/recargar-saldo'
    | '/saldo'
    | '/producto/$id'
    | '/api/public/ip'
    | '/api/public/ip-watch'
    | '/api/public/img/$'
    | '/api/public/telegram/webhook'
    | '/api/public/webhooks/binance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  MisPedidosRoute: typeof MisPedidosRoute
  RecargarSaldoRoute: typeof RecargarSaldoRoute
  SaldoRoute: typeof SaldoRoute
  ProductoIdRoute: typeof ProductoIdRoute
  ApiPublicIpRoute: typeof ApiPublicIpRoute
  ApiPublicIpWatchRoute: typeof ApiPublicIpWatchRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicWebhooksBinanceRoute: typeof ApiPublicWebhooksBinanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pedidos': {
      id: '/mis-pedidos'
      path: '/mis-pedidos'
      fullPath: '/mis-pedidos'
      preLoaderRoute: typeof MisPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recargar-saldo': {
      id: '/recargar-saldo'
      path: '/recargar-saldo'
      fullPath: '/recargar-saldo'
      preLoaderRoute: typeof RecargarSaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saldo': {
      id: '/saldo'
      path: '/saldo'
      fullPath: '/saldo'
      preLoaderRoute: typeof SaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ip': {
      id: '/api/public/ip'
      path: '/api/public/ip'
      fullPath: '/api/public/ip'
      preLoaderRoute: typeof ApiPublicIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ip-watch': {
      id: '/api/public/ip-watch'
      path: '/api/public/ip-watch'
      fullPath: '/api/public/ip-watch'
      preLoaderRoute: typeof ApiPublicIpWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/binance': {
      id: '/api/public/webhooks/binance'
      path: '/api/public/webhooks/binance'
      fullPath: '/api/public/webhooks/binance'
      preLoaderRoute: typeof ApiPublicWebhooksBinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  MisPedidosRoute: MisPedidosRoute,
  RecargarSaldoRoute: RecargarSaldoRoute,
  SaldoRoute: SaldoRoute,
  ProductoIdRoute: ProductoIdRoute,
  ApiPublicIpRoute: ApiPublicIpRoute,
  ApiPublicIpWatchRoute: ApiPublicIpWatchRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicWebhooksBinanceRoute: ApiPublicWebhooksBinanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
